### PR TITLE
sqltrie: make recursive subtrie traversal lazy

### PR DESCRIPTION
**Pull request by pmrowla**
Fixes https://github.com/iterative/dvc/issues/9914

- makes `sqltrie.AbstractTrie.traverse()` API compatible with pygtrie
- makes `SQLiteTrie.traverse()` subtrie traversal behavior equivalent to pygtrie
    - subtrie traversal is skipped when the caller's `node_factory` does not iterate on `children`
    - traversing one level of depth only requires one SQL query for the parent (child nodes are not re-queried)
- `SQLiteTrie.items()` and `__len__()` now use the same logic as `traverse()` instead of `items.sql`
    - added benchmark for `len(trie)`

### CODE REVIEW

**Comment by dberenbaum** [comment]
Is there a performance comparison available? And can we add any tests?

**Comment by efiop** [comment]
@dberenbaum Yeah, @pmrowla mentioned that results were pretty much the same as in https://github.com/iterative/sqltrie/pull/21 . I've enabled benchmarks in CI as well and one of us will add a traverse benchmark.

**Comment by efiop** [comment]
Added benchmarks in https://github.com/iterative/sqltrie/pull/27 . Without this PR:

```
-------------------------------------------------------------------------------------- benchmark 'test_traverse': 2 tests -------------------------------------------------------------------------------------
Name (time in us)                    Min                   Max                  Mean             StdDev                Median                IQR            Outliers          OPS            Rounds  Iterations
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_traverse[PyGTrie]           28.9170 (1.0)         55.5840 (1.0)         29.5493 (1.0)       0.6483 (1.0)         29.4590 (1.0)       0.2080 (1.0)       508;592  33,841.7058 (1.0)       16405           1
test_traverse[SQLiteTrie]     1,203.6250 (41.62)    1,438.8750 (25.89)    1,223.2473 (41.40)    15.8361 (24.43)    1,220.5830 (41.43)    13.6970 (65.85)       52;18     817.4962 (0.02)        449           1
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

with this PR:

```
--------------------------------------------------------------------------------- benchmark 'test_traverse': 2 tests --------------------------------------------------------------------------------
Name (time in us)                 Min                 Max                Mean             StdDev             Median               IQR            Outliers  OPS (Kops/s)            Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_traverse[PyGTrie]        27.5000 (1.0)       82.9160 (1.0)       28.1661 (1.0)       1.0373 (1.0)      28.0000 (1.0)      0.2080 (1.0)      669;1179       35.5037 (1.0)       14044           1
test_traverse[SQLiteTrie]     95.3330 (3.47)     450.7910 (5.44)     100.7336 (3.58)     13.9978 (13.49)    99.0000 (3.54)     3.7500 (18.03)     217;301        9.9272 (0.28)       4378           1
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by efiop** [comment]
Before:
```
------------------------------------------------------------------------------------------ benchmark 'test_traverse': 2 tests ------------------------------------------------------------------------------------------
Name (time in ms)                      Min                     Max                    Mean                StdDev                  Median                   IQR            Outliers     OPS            Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_traverse[PyGTrie]            427.4635 (1.0)          430.3030 (1.0)          428.9901 (1.0)          1.0631 (1.0)          429.3343 (1.0)          1.3280 (1.0)           2;0  2.3311 (1.0)           5           1
test_traverse[SQLiteTrie]     121,870.5093 (285.10)   127,292.6533 (295.82)   124,073.0798 (289.22)   2,391.6569 (>1000.0)  122,680.0896 (285.74)   3,877.1463 (>1000.0)       1;0  0.0081 (0.00)          5           1
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

```

after

```
----------------------------------------------------------------------------------- benchmark 'test_traverse': 2 tests -----------------------------------------------------------------------------------
Name (time in ms)                    Min                   Max                  Mean             StdDev                Median                IQR            Outliers     OPS            Rounds  Iterations
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_traverse[PyGTrie]          420.6988 (1.0)        426.1195 (1.0)        422.2674 (1.0)       2.2178 (1.0)        421.6570 (1.0)       2.1787 (1.0)           1;0  2.3682 (1.0)           5           1
test_traverse[SQLiteTrie]     3,153.3745 (7.50)     3,359.1128 (7.88)     3,205.5099 (7.59)     86.9614 (39.21)    3,167.2150 (7.51)     74.5595 (34.22)         1;1  0.3120 (0.13)          5           1
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

so ~x40 improvement. Great work @pmrowla

**Comment by pmrowla** [comment]
This PR no longer changes the existing `_ids` dict caching (caching them is probably still worthwhile in the future, but we would need to figure out a good max cache size)

On my machine

main:
```
test_traverse[SQLiteTrie]     117,678,626.1670 (>1000.0)  118,369,516.7500 (>1000.0)  118,091,849.7168 (>1000.0)  254,566.4453 (>1000.0)  118,144,413.7080 (>1000.0)  248,889.3015 (>1000.0)       2;0        0.0085 (0.00)          5           1
test_items[SQLiteTrie]            789,793.0000 (>1000.0)      802,767.7910 (>1000.0)      794,405.0332 (>1000.0)    5,221.0807 (>1000.0)      794,248.9580 (>1000.0)    6,816.5725 (>1000.0)       1;0        1.2588 (0.00)          5           1
test_len[SQLiteTrie]     666.8490 (53.23)    708.1732 (42.27)    688.1017 (54.15)    16.3588 (27.24)    688.3111 (54.67)    25.8973 (890.76)        2;0   1.4533 (0.02)          5           1
```

this PR:

```
test_traverse[SQLiteTrie]       310,249.2500 (>1000.0)    323,367.9580 (>1000.0)    318,067.3748 (>1000.0)   4,980.9523 (>1000.0)    319,977.6660 (>1000.0)   5,917.8650 (>1000.0)       2;0        3.1440 (0.00)          5           1
test_items[SQLiteTrie]          262,559.7910 (>1000.0)    280,466.7910 (>1000.0)    270,019.0662 (>1000.0)   6,822.9580 (>1000.0)    267,806.7080 (>1000.0)   8,748.4058 (>1000.0)       2;0        3.7034 (0.00)          5           1
test_len[SQLiteTrie]     248.8182 (19.83)    262.2762 (15.89)    258.0292 (20.28)    5.7484 (9.60)     261.4718 (20.77)    7.6449 (186.18)        1;0   3.8755 (0.05)          5           1
```

The real-world DVC numbers are essentially still the same as the pure-pygtrie view version from #21, where the `dvc fetch` regression from 3.10 is resolved (~15.5s to fetch 25k files down from 1.5min)

**Review by efiop — APPROVED** [review]

**Pull request merged**
