### PR TITLE
sqltrie: return an in-memory pygtrie as view()

### PR DESCRIPTION
**Pull request by pmrowla**
related: https://github.com/iterative/dvc/issues/9914

This is a workaround to avoid the heavy sql temporary table creation from `traverse()` that's needed when using views. The sql for iterating over the entire trie is fast, so building an entire pygtrie in memory for the view is cheap in terms of performance. The downside here is that the view no longer reflects any changes made to the original sqltrie after the view is instantiated. I think it's probably worth revisiting the traverse sql at some point, but in the short term I don't think this workaround would block anything in dvc-data.

dvc main with sqltrie main (~25k file local fetch):
```
$ time dvc pull
Collecting                                                                                                                          |25.0k [01:31,  274entry/s]
Fetching
Building workspace index                                                                                                             |0.00 [00:00,    ?entry/s]
Comparing indexes                                                                                                                  |25.0k [00:00, 70.7kentry/s]
Applying changes                                                                                                                    |25.0k [00:06, 3.94kfile/s]
A       cats_dogs/
1 file added and 24972 files fetched
dvc pull  84.13s user 18.57s system 96% cpu 1:46.85 total
```

with this PR:
```
$ time dvc pull
Collecting                                                                                                                         |25.0k [00:00, 57.7kentry/s]
Fetching
Building workspace index                                                                                                             |0.00 [00:00,    ?entry/s]
Comparing indexes                                                                                                                  |25.0k [00:00, 98.2kentry/s]
Applying changes                                                                                                                    |25.0k [00:06, 3.98kfile/s]
A       cats_dogs/
1 file added and 24972 files fetched
dvc pull  4.78s user 7.12s system 75% cpu 15.745 total
```

### CODE REVIEW

**Comment by pmrowla** [comment]
marked as draft, this breaks tests downstream in dvc but not in dvc-data

**Comment by efiop** [comment]
Yeah, not reflecting the changes back is a deal breaker here :(

**Comment by efiop** [comment]
>Yeah, not reflecting the changes back is a deal breaker here :(


Though I guess there are different purposes that we are currently mixing up by using one data_index db. So i'll take this back.

**Comment by efiop** [comment]
@pmrowla Do you think it would make sense to implement a sql-based IndexView for this?

**Comment by pmrowla** [comment]
@efiop I'm still looking into this, and yeah I think we'll need something along those lines

**Pull request closed without merging**
